project:
  type: website
  
filters:
  - quarto

website:
  title: "Building a DIY BtM Datalogger for Moss & Lichen Water Monitoring"
  sidebar:
    style: floating  # or "docked"
    search: true
    contents:
      - text: "Home"
        file: index.qmd
      - prerequisites.qmd
      - intro.qmd
      - hw.qmd
      - sw.qmd
      - sample-measurements.qmd
      - calibration.qmd

format:
  html:
    theme: [sandstone, styles.scss]
    toc: true




