---
title: "Introduction"
format: html
---

# 1. Why a BtM?

-   **Problem to solve:** Existing commercial solutions were expensive and did not fully meet our specific needs. They offered limited flexibility and closed architectures, which constrained our research applications.

-   **Our approach: Free/Libre and Open Source Development**\
    We chose to develop our own solution using open hardware and open software.

    Advantages include:

    -   Lower cost

    -   Transparency and reproducibility

    -   Full adaptability to specific research needs

    -   Collaborative improvement and customization

<!--
Las soluciones comerciales no servían para nuestra aplicación:
- Pines
- 8 medidas
- 
-->

# 2. What is a BtM?

The BtM (Bryolichen Temperature Moisture board) is:

-   A **datalogger** with:

    -   A temperature/humidity sensor for ambient conditions

    -   **8 activity detection channels** based on soil or organism water content

### How do we measure "activity"?

-   **Water content–activity correlation:** Biological activity is closely related to water content in soils and substrates.

-   **Water content = Conductance:** By measuring **electrical conductance**, we estimate water content, which serves as a proxy for activity.

-   BtM includes both **software and hardware** components, both of them open-source.

### How is this workshop organized?

#### Part A: BtM Tech Details

-   We will show you how to operate the BtM and some tech details for both **field and laboratory** setups.

#### Part B: Data Retrievement and Data Analysis Demonstration

-   We will explore the code used to **retrieve and analyze data** using the BtM.


