---
title: "Workshop Materials"
format: html
editor: visual
---

## General stuff

# BtMs & electronics

-   Computer with arduino (ﾃ］gel)
-   4 BtMs
-   MicroSD adapters (6 in a bag)
-   3 FTDI adapters (if possible, 4) with cable
-   3 Sensors with caps
-   Protoboard
-   Resistors (2 sets pinned)
-   2 BtM boards in different mount stages
-   2 microSD with card adapter
-   Mini clamps
-   Silicon cable
-   Regular cable
-   3 chargers
-   Thermoretractable case

# Tools

-   Scissors
-   2 Wire stripper
-   2 solders
-   Solder stand
-   Tin
-   Solder sponge
-   Screwdriver set
-   2 big screwdrivers
-   Blue marker
-   Multimeter
-   Pliers
-   Fan
-   2 water sprays
-   6 pipettes
-   10 extra batteries
-   2 scotch tape (black & white)

# Samples

-   Moss
-   Lichen
-   Soil (bag + 3 seed pots)
-   3 Plastic trays


# \_\_\_\_\_\_\_\_\_

## A1 Solder practice

-   Tin
-   Solder
-   Solder sponge
-   Soil pins to solder
-   Cable to solder
-   Thermoretractable case
-   Pliers (alicates)

## A2 BtM measurements

-   BtM
-   Computer with arduino IDE (ﾃ］gel)

## B1 Dessication curve

-   Moss
-   Fan
-   Destilled water
-   FTDI adapter
-   BtM with pins
-   Computer with arduino IDE (ﾃ］gel)

## B2 Calibration: resistor calibration

-   Protoboard
-   Resistors (2 sets pinned)
-   Computer with arduino IDE (ﾃ］gel)
-   FTDI adapter

## 32 Calibration: Precipitation simulation

-   Samples:
    -   Moss
    -   Lichen
    -   Soil
-   3 water sprays
-   3 BtM with different probes:
    -   Pins for mosses
    -   Clamps for lichens
    -   Soil pins for soils
