---
title: "Requirements for the Workshop"
format: html
---

# Requirements for the Workshop

To ensure a smooth and productive experience during the workshop, please prepare the following items **in advance**:

-   **Computer**: Please bring a laptop (We recommend Linux, but can be done in Windows or Mac). Make sure your device has at least one USB port and **administrative privileges** to install software.

-   **Arduino IDE**: We will be using the Arduino 2 IDE. Please install it in advance by following these steps:

    1.  Go to the [official Arduino IDE 2 download page](https://www.arduino.cc/en/software)

    2.  Download the installer for your operating system.

    3.  Follow the [installation instructions specific to your platform](https://docs.arduino.cc/software/ide-v2/tutorials/getting-started/ide-v2-downloading-and-installing/)

    4.  Make sure the IDE launches correctly after installation. Check the [Getting started section](https://docs.arduino.cc/software/ide-v2/tutorials/getting-started-ide-v2/).

    5.  Copy the libraries folder in:

        1.   `Documents/Arduino/` (Windows)

        2.  `~/Arduino/` (Linux & Mac)

-   **Code**: Please **download the workshop repository in advance** in using one of the following formats: [ZIP File](https://github.com/angellareo/workshop-btm/archive/refs/heads/main.zip) or [GitHub Link](https://github.com/angellareo/workshop-btm). Although [the original BtM code](https://github.com/united-ecology/btmboard) can also be used.

    -   Make sure you get the contents (or extract them if you downloaded the ZIP) and browse the folder to verify that everything was downloaded correctly. **Remember the path of this directory**.

If you have any questions or need technical support before the workshop, feel free to contact us at: angel.lareo\@uam.es / maria.leomontes\@gmail.com
